### PR TITLE
Fix for newer Android NDKs

### PR DESCRIPTION
**Pull request by xsacha**

### CODE REVIEW

**Comment by ruslo** [comment]
What NDK is newer? Testing looks good for NDK r10e and NDK r15c:
* https://travis-ci.org/ingenue/hunter/builds/313940790?utm_source=github_status&utm_medium=notification

**Comment by xsacha** [comment]
Test probably isn't extensive enough for this particular problem.
When unified headers is on and you try to use filesystem, it complains about missing functions (eg. fseeko64, ftello64) when these defines are set.

On older NDKs (r15c inclusive), I worked around the issue by disabling unified headers but r16 no longer allows you to.

This is the minizip issue: https://github.com/nmoinvaz/minizip/issues/137
However it is no longer relevant to minizip 2 as these files don't exist.

Here's one of the several NDK issues: https://github.com/android-ndk/ndk/issues/364
This one succinctly identified the problem and shows the fix.

**Comment by ruslo** [comment]
> However it is no longer relevant to minizip 2 as these files don't exist.

May be it make sense to update fork to something that includes this change?
* https://github.com/flokart-world/minizip/commit/04fe4a8630007bd02f0e50942637f8554d2dbe0f

**Comment by ruslo** [comment]
> flokart-world/minizip@04fe4a8

Wait, it's not an upstream repository. This one:
* https://github.com/nmoinvaz/minizip/commit/5083bef59fd9661f79941c99ff1ecded83d72409

**Comment by xsacha** [comment]
Makes more sense

**Comment by ruslo** [comment]
Branch `hunter-5083bef` created, please send hunterization patches there:
* https://github.com/hunter-packages/minizip/tree/hunter-5083bef

**Pull request closed without merging**
